# This rule is not used by the project nic-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over reconcilers.nebari.dev.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: nic-operator
    app.kubernetes.io/managed-by: kustomize
  name: nebariapp-admin-role
rules:
- apiGroups:
  - reconcilers.nebari.dev
  resources:
  - nebariapps
  verbs:
  - '*'
- apiGroups:
  - reconcilers.nebari.dev
  resources:
  - nebariapps/status
  verbs:
  - get
