apiVersion: reconcilers.nebari.dev/v1
kind: NebariApp
metadata:
  labels:
    app.kubernetes.io/name: nic-operator
    app.kubernetes.io/managed-by: kustomize
  name: nebariapp-sample
spec:
  # TODO(user): Add fields here
